import 'package:flutter_riverpod/legacy.dart';
export 'package:flutter_riverpod/legacy.dart' show ChangeNotifierProvider;
import 'auth_provider.dart';
import 'product_provider.dart';
import 'cart_provider.dart';
import 'order_provider.dart';
import 'wallet_provider.dart';
import 'message_provider.dart';
import 'seller_provider.dart';
import 'sound_provider.dart';
import 'home_provider.dart';
import 'business_profile_provider.dart';
import 'curated_provider.dart';
import 'carousel_provider.dart';
import 'block_provider.dart';
import 'purchase_permission_provider.dart';
import 'explore_provider.dart';
import 'service_provider.dart';
import 'verification_provider.dart';
import 'video_provider.dart';
import 'chat_background_provider.dart';

final authProvider = ChangeNotifierProvider((ref) => AuthProvider());
final productProvider = ChangeNotifierProvider((ref) => ProductProvider());
final cartProvider = ChangeNotifierProvider((ref) => CartProvider());
final orderProvider = ChangeNotifierProvider((ref) => OrderProvider());
final walletProvider = ChangeNotifierProvider((ref) => WalletProvider());
final messageProvider = ChangeNotifierProvider((ref) => MessageProvider());
final sellerProvider = ChangeNotifierProvider((ref) => SellerProvider());
final soundProvider = ChangeNotifierProvider((ref) => SoundProvider());
final homeProvider = ChangeNotifierProvider((ref) => HomeProvider());
final businessProfileProvider = ChangeNotifierProvider((ref) => BusinessProfileProvider());
final curatedProvider = ChangeNotifierProvider((ref) => CuratedProvider());
final carouselProvider = ChangeNotifierProvider((ref) => CarouselProvider());
final blockProvider = ChangeNotifierProvider((ref) => BlockProvider());
final purchasePermissionProvider = ChangeNotifierProvider((ref) => PurchasePermissionProvider());
final exploreProvider = ChangeNotifierProvider((ref) => ExploreState());
final serviceProvider = ChangeNotifierProvider((ref) => ServiceProvider());
final verificationProvider = ChangeNotifierProvider((ref) => VerificationProvider());
final videoProvider = ChangeNotifierProvider((ref) => VideoProvider());
final chatBackgroundProvider = ChangeNotifierProvider((ref) => ChatBackgroundProvider());
final exploreRefreshProvider = StateProvider<int>((ref) => 0);
