// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABpA0QPLYCWTpFK4nj2LqTNF1wUZcHYXU',
    appId: '1:658847293429:web:920ff32ee502cc2678cabc',
    messagingSenderId: '658847293429',
    projectId: 'instiy-f0295',
    authDomain: 'instiy-f0295.firebaseapp.com',
    storageBucket: 'instiy-f0295.firebasestorage.app',
    measurementId: 'G-X9WKQ6DPGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrqqHMm-JD-WfsmdDJq2izeOEjBUO-Ps',
    appId: '1:658847293429:android:fae62c130aff8ff278cabc',
    messagingSenderId: '658847293429',
    projectId: 'instiy-f0295',
    storageBucket: 'instiy-f0295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCujZxWQyGiUXdkXOXLBohPJsBfGLg4SG0',
    appId: '1:658847293429:ios:1e1ea49b2f78920d78cabc',
    messagingSenderId: '658847293429',
    projectId: 'instiy-f0295',
    storageBucket: 'instiy-f0295.firebasestorage.app',
    androidClientId: '658847293429-cb5mrrgpomhak1154rdjbb1h4vf61p9h.apps.googleusercontent.com',
    iosClientId: '658847293429-sl27t5lj2ds0ckh77suu6dkrms54ter3.apps.googleusercontent.com',
    iosBundleId: 'com.instiy',
  );
}
