// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	R2_PUBLIC_URL: string;
	R2_BUCKET_NAME: string;
	R2_BUCKET: R2Bucket;
	R2_ENDPOINT?: string;
	R2_ACCESS_KEY_ID?: string;
	PAYSTACK_SECRET_KEY?: string;
	PAYSTACK_PUBLIC_KEY?: string;
	HUBTEL_CLIENT_ID?: string;
	HUBTEL_CLIENT_SECRET?: string;
	HUBTEL_SENDER_ID?: string;
	FCM_SERVICE_ACCOUNT_KEY?: string;
	GIPHY_API_KEY?: string;
	REDIRECT_URL?: string;
	APP_VERSION?: string;
	ANDROID_CERT_SHA256?: string;
	APPLE_TEAM_ID?: string;
	TURN_URL?: string;
	TURN_USERNAME?: string;
	TURN_CREDENTIAL?: string;
}
