default_platform(:android)

platform :android do
  desc "Upload an already-built AAB to the Play Store internal testing track"
  lane :internal do
    upload_to_play_store(
      track: "internal",
      aab: ENV.fetch("AAB_PATH"),
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
